/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export interface CdrColorTextTokens {
  "color-text-brand": string;
  "color-text-inverse": string;
  "color-text-neutral-bold": string;
  "color-text-neutral-emphasis": string;
  "color-text-neutral-muted": string;
  "color-text-success": string;
  "color-text-warning": string;
}
