/* This file is auto-generated by Style Dictionary. Do not edit manually. */

import type { TokenDocsMap } from "../token-dictionary.js";
import type { CdrColorNavigationTokenName } from "./cdr-color-navigation.names.js";

export type CdrColorNavigationTokenDocs = TokenDocsMap<CdrColorNavigationTokenName>;
