/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export interface CdrTextSizeFluidTokens {
  "text-size-fluid-fluid-100": string;
  "text-size-fluid-fluid-200": string;
  "text-size-fluid-fluid-300": string;
  "text-size-fluid-fluid-400": string;
  "text-size-fluid-fluid-500": string;
}
