/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export interface CdrSpacingLayoutTokens {
  "spacing-layout-lg": string;
  "spacing-layout-md": string;
  "spacing-layout-sm": string;
  "spacing-layout-xl": string;
}
