/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export interface CdrColorActionTokens {
  "color-action-brand-faint": string;
  "color-action-edge-brand": string;
  "color-action-edge-inverse": string;
  "color-action-edge-neutral": string;
  "color-action-inverse": string;
  "color-action-neutral-faint": string;
  "color-action-on-brand": string;
  "color-action-on-link": string;
  "color-action-on-neutral": string;
  "color-action-sale": string;
}
