/* This file is auto-generated by Style Dictionary. Do not edit manually. */

import type { TokenDocsMap } from "../token-dictionary.js";
import type { CdrTextWeightTokenName } from "./cdr-text-weight.names.js";

export type CdrTextWeightTokenDocs = TokenDocsMap<CdrTextWeightTokenName>;
