/* This file is auto-generated by Style Dictionary. Do not edit manually. */

import type { TokenDocsMap } from "../token-dictionary.js";
import type { CdrTextLineHeightTokenName } from "./cdr-text-line-height.names.js";

export type CdrTextLineHeightTokenDocs = TokenDocsMap<CdrTextLineHeightTokenName>;
