/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export type Theme = "rei-dot-com"
export type Platform = "web" | "ios" | "android"
export type Responsibility = "foundations"

export type FoundationModule =
| "cdr-spacing-component"
| "cdr-spacing-layout"
| "cdr-spacing-scale"
| "cdr-spacing-static"
| "cdr-text-family"
| "cdr-text-letter-spacing"
| "cdr-text-line-height"
| "cdr-text-size-fluid"
| "cdr-text-size-static"
| "cdr-text-style"
| "cdr-text-weight";

export type TTheme = Theme;
export type TPlatform = Platform;
export type TResponsibility = Responsibility;
export type TModule = FoundationModule;

export interface TokenDocumentation {
  summary?: string;
  usage?: string;
  design?: string;
  aliases?: string[];
}

export type TokenMap = Record<string, string>;

export type TokenDocsMap<TTokenName extends string = string> = Partial<
  Record<TTokenName, TokenDocumentation>
>;

export interface TokenDictionary<
  TTheme extends Theme,
  TPlatform extends Platform,
  TResponsibility extends Responsibility,
  TModuleName extends string,
  TTokens extends TokenMap,
  TTokenName extends keyof TTokens & string = keyof TTokens & string,
> {
  theme: TTheme;
  platform: TPlatform;
  responsibility: TResponsibility;
  module: TModuleName;
  tokens: TTokens;
  docs?: TokenDocsMap<TTokenName>;
}
