/**
 * load-canonical.ts
 *
 * Utility to load the canonical.json token file at build time.
 * This allows stories to use real tokens instead of hardcoded fixtures.
 *
 * The canonical.json is generated by the token normalization pipeline
 * (sd/src/normalization/normalize.ts) and contains the authoritative
 * section-nested token structure.
 *
 * Implementation: Directly imports the canonical.json as a module.
 * Vite handles this transparently, inlining the JSON at build time.
 */

// Import canonical.json directly as a JavaScript module
// Vite's JSON loader converts it to: export default { ... }
import canonicalData from "../../sd/tokens/canonical.json";

/**
 * Load the canonical token tree.
 * The data is already loaded by Vite's JSON plugin.
 */
export function loadCanonical(): Record<string, unknown> {
  return canonicalData as Record<string, unknown>;
}
