/**
 * load-canonical.ts
 *
 * Utility to load the canonical.json token file at build time.
 * This allows stories to use real tokens instead of hardcoded fixtures.
 *
 * The canonical.json is generated by the token normalization pipeline
 * (sd/src/normalization/normalize.ts) and contains the authoritative
 * section-nested token structure.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const canonicalPath = path.resolve(__dirname, "../../sd/tokens/canonical.json");

/**
 * Load the canonical token tree synchronously.
 * Called at build time before stories render.
 * Throws if canonical.json doesn't exist (e.g. normalize.ts hasn't been run yet).
 */
export function loadCanonical(): Record<string, unknown> {
  if (!fs.existsSync(canonicalPath)) {
    throw new Error(
      `canonical.json not found at ${canonicalPath}. ` +
      `Run 'pnpm tokens:normalize' first to generate it.`,
    );
  }
  return JSON.parse(fs.readFileSync(canonicalPath, "utf-8")) as Record<string, unknown>;
}
