/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export type Theme = "rei-dot-com";
export type Platform = "web" | "ios" | "android";
export type Responsibility = "foundations";

export type FoundationModule =
  | "cdr-color-border"
  | "cdr-color-surface"
  | "cdr-color-text"
  | "cdr-spacing-component"
  | "cdr-spacing-layout"
  | "cdr-spacing-scale";
