import type { TransformedToken } from "style-dictionary";
import StyleDictionary from "style-dictionary";

StyleDictionary.registerFormat({
  name: "objc/header-color",
  format: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(
      (token: TransformedToken) => token.path[0] === "color"
    );

    const enumValues = colorTokens
      .map((token: TransformedToken) => {
        const enumName = token.name.replace(/([A-Z])/g, "_$1").toUpperCase().replace(/^_/, "");
        return `    ${enumName} = ${colorTokens.indexOf(token)}`;
      })
      .join(",\n");

    return [
      "// Automatically generated by Cedar Token Pipeline - CocoaPods (Flagship)",
      "// Objective-C header for enum-based color access",
      "#import <Foundation/Foundation.h>",
      "#import <UIKit/UIKit.h>",
      "",
      "typedef NS_ENUM(NSInteger, CdrColorName) {",
      enumValues,
      "};",
      "",
      "@interface CdrColor : NSObject",
      "",
      "+ (UIColor *)color:(CdrColorName)name;",
      "",
      "@end",
    ].join("\n");
  },
});
