import type { TransformedToken } from "style-dictionary";
import StyleDictionary from "style-dictionary";

StyleDictionary.registerFormat({
  name: "swift/enum-color",
  format: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(
      (token: TransformedToken) => token.path[0] === "color"
    );

    const enumValues = colorTokens
      .map((token: TransformedToken) => {
        const camelName = token.name;
        return `    ${camelName} = ${token.name.replace(/([A-Z])/g, "_$1").toUpperCase().replace(/^_/, "")}`;
      })
      .join(",\n");

    return [
      "// Automatically generated by Cedar Token Pipeline - CocoaPods (Flagship)",
      "// Enum-based color access for Objective-C compatibility",
      "import UIKit",
      "import Foundation",
      "",
      "public enum CdrColorName: Int {",
      enumValues,
      "}",
      "",
      "@objc public class CdrColor: NSObject {",
      "    @objc public static func color(_ name: CdrColorName) -> UIColor {",
      "        let colorName = colorNameString(for: name)",
      "        let bundle = Bundle(for: CdrColor.self)",
      "        guard let color = UIColor(named: colorName, in: bundle, compatibleWith: nil) else {",
      "            return .clear",
      "        }",
      "        return color",
      "    }",
      "    ",
      "    @objc public static func values() -> [UIColor] {",
      "        return (0...\\(CdrColorName.values.count - 1)).compactMap { rawValue in",
      "            guard let colorName = CdrColorName(rawValue: rawValue) else { return nil }",
      "            return color(colorName)",
      "        }",
      "    }",
      "    ",
      "    private static func colorNameString(for name: CdrColorName) -> String {",
      "        switch name {",
      ...colorTokens.map((token: TransformedToken) => {
        const camelName = token.name;
        const enumName = camelName.replace(/([A-Z])/g, "_$1").toUpperCase().replace(/^_/, "");
        return `        case .${enumName}: return "cdr-${token.name}"`;
      }).join("\n"),
      "        }",
      "    }",
      "}",
    ].join("\n");
  },
});
