/* This file is auto-generated by Style Dictionary. Do not edit manually. */

import type { TokenDocsMap } from "../token-dictionary.js";
import type { CdrSpacingLayoutTokenName } from "./cdr-spacing-layout.names.js";

export type CdrSpacingLayoutTokenDocs = TokenDocsMap<CdrSpacingLayoutTokenName>;
