/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export type CdrTextSizeFluidTokenName =
  | "text-size-fluid-fluid-100"
  | "text-size-fluid-fluid-200"
  | "text-size-fluid-fluid-300"
  | "text-size-fluid-fluid-400"
  | "text-size-fluid-fluid-500";
