/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export type CdrTextLineHeightTokenName =
  | "text-line-height-height-0"
  | "text-line-height-height-1"
  | "text-line-height-height-2"
  | "text-line-height-height-3"
  | "text-line-height-height-4"
  | "text-line-height-height-5";
