/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export type CdrColorTextTokenName =
  | "color-text-brand"
  | "color-text-inverse"
  | "color-text-neutral-bold"
  | "color-text-neutral-emphasis"
  | "color-text-neutral-muted"
  | "color-text-success"
  | "color-text-warning";
