/* This file is auto-generated by Style Dictionary. Do not edit manually. */

import type { TokenDocsMap } from "../token-dictionary.js";
import type { CdrTextFamilyTokenName } from "./cdr-text-family.names.js";

export type CdrTextFamilyTokenDocs = TokenDocsMap<CdrTextFamilyTokenName>;
