/* This file is auto-generated by Style Dictionary. Do not edit manually. */

import type { TokenDocsMap } from "../token-dictionary.js";
import type { CdrSpacingStaticTokenName } from "./cdr-spacing-static.names.js";

export type CdrSpacingStaticTokenDocs = TokenDocsMap<CdrSpacingStaticTokenName>;
