/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export type CdrColorNavigationTokenName =
  | "color-navigation-edge-brand"
  | "color-navigation-edge-neutral"
  | "color-navigation-on-neutral";
