/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export type CdrTextSizeStaticTokenName =
  | "text-size-static-static-100"
  | "text-size-static-static-200"
  | "text-size-static-static-300"
  | "text-size-static-static-400"
  | "text-size-static-static-500";
