/* This file is auto-generated by Style Dictionary. Do not edit manually. */

import type { TokenDocsMap } from "../token-dictionary.js";
import type { CdrColorOverlayTokenName } from "./cdr-color-overlay.names.js";

export type CdrColorOverlayTokenDocs = TokenDocsMap<CdrColorOverlayTokenName>;
