/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export interface CdrColorSurfaceTokens {
  "color-surface-brand-faint": string;
  "color-surface-edge-neutral-bold": string;
  "color-surface-neutral-base": string;
  "color-surface-neutral-bold": string;
  "color-surface-neutral-faint": string;
}
