/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export interface CdrColorSelectionTokens {
  "color-selection-edge-neutral": string;
  "color-selection-neutral-bold": string;
  "color-selection-neutral-faint": string;
  "color-selection-on-neutral-bold": string;
}
