/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export interface CdrColorFeedbackTokens {
  "color-feedback-edge-error": string;
  "color-feedback-edge-success": string;
  "color-feedback-edge-warning": string;
  "color-feedback-error-bold": string;
  "color-feedback-error-faint": string;
  "color-feedback-info-bold": string;
  "color-feedback-info-faint": string;
  "color-feedback-on-error": string;
  "color-feedback-on-info": string;
  "color-feedback-success-bold": string;
  "color-feedback-success-faint": string;
  "color-feedback-warning-bold": string;
  "color-feedback-warning-faint": string;
}
