/* This file is auto-generated by Style Dictionary. Do not edit manually. */

export interface CdrTextLineHeightTokens {
  "text-line-height-height-0": string;
  "text-line-height-height-1": string;
  "text-line-height-height-2": string;
  "text-line-height-height-3": string;
  "text-line-height-height-4": string;
  "text-line-height-height-5": string;
}
